services:

  db-library:
    image: postgres:14
    container_name: db-library
    environment:
      POSTGRES_PASSWORD: "secret"
      POSTGRES_USER: "admin"
      POSTGRES_DB: "library"
      TZ: "America/Bogota"
    volumes:
      - ./db/data:/var/lib/postgresql/data
    networks:
      - library-network

  redis:
    image: redis:7
    container_name: redis
    networks:
      - library-network

networks:
  library-network:
    driver: bridge