package com.jeyson.Users.Domain.Constants.Security;


public enum Permission {
    MONITOR_APP,
    CREATE_ADMIN,
    CREATE_LIBRARIAN,
    CREATE_CUSTOMER,
    GET_ALL_USERS,
    GET_ONE_USER,
    UPDATE_USERS,
    DELETE_USERS,
    CREATE_BOOKCASE,
    DELETE_BOOKCASE,
    UPDATE_BOOKCASE,
    GET_BOOKCASES,
    CREATE_BOOK,
    DELETE_BOOK,
    UPDATE_BOOK,
    GET_BOOKS,
    CREATE_RENT,
    DELETE_RENT,
    UPDATE_RENT,
    GET_RENT
}